### ISSUE TITLE
Blending Factor

### ISSUE THREAD

**Issue by NekoMale** [Rabbid76/c_sharp_opengl#1]
The project doesn't compile cause it doesn't find BlendingFactor Class/Enum.

The error is at line:
`GL.BlendFunc(BlendingFactor.SrcAlpha, BlendingFactor.OneMinusSrcAlpha);`
into DrawText's OnUpdateFrame method.

Should be changed in:
`GL.BlendFunc(BlendingFactorSrc.SrcAlpha, BlendingFactorDest.OneMinusSrcAlpha);`

**Comment by Rabbid76** [comment]
That seems to be an issue related to the OpenTK version, assembly or namespace. The project uses OpenTK 3.1.0 and  `OpenTK.Graphics.OpenGL4`.
Strangely enough, in that has it has to be used

```c#
GL.BlendFunc(BlendingFactor.SrcAlpha, BlendingFactor.OneMinusSrcAlpha);
```

**Comment by Rabbid76** [comment]
#https://github.com/Rabbid76/c_sharp_opengl/commit/4425b65eeaa16f837d6b952070ce3cbfadebe750
